#!/bin/sh
#

if [ "$1" == "start"  ]; then

#https://developer.ridgerun.com/wiki/index.php/High_performance_SD_card_tuning_using_the_EXT4_file_system

#echo 100 > /proc/sys/vm/dirty_writeback_centisecs 
#echo 100 > /proc/sys/vm/dirty_expire_centisecs

if [ -f "/secondboot" ]; then
	echo "Second boot... ";
	rm /secondboot
#	/usr/sbin/mkfs.ext2 -q -F /dev/mmcblk0p3
	mkfs.ext4 -q -F /dev/mmcblk0p3
	tune2fs -o journal_data_writeback /dev/mmcblk0p3
	tune2fs -O ^has_journal /dev/mmcblk0p3
	e2fsck -f /dev/mmcblk0p3

	mkdir /rpicopter
	chmod 777 /rpicopter
	mount /dev/mmcblk0p3 /rpicopter
	mkdir /rpicopter/log
	chmod 777 /rpicopter/log
	mkdir /rpicopter/cam
	chmod 777 /rpicopter/cam
	mkdir /rpicopter/tmp
	chmod 777 /rpicopter/tmp
#	cp /etc/avrminicopter/* /rpicopter/
#	echo "/dev/mmcblk0p3       /rpicopter              ext2	async,rw,noauto         0      0" >> /etc/fstab
	
	echo "/dev/mmcblk0p3       /rpicopter              ext4	noatime,nodiratime,data=writeback         0      0" >> /etc/fstab
	rm /var/run/messagebus.pid
	echo "Second boot done!";
	/bin/sync;bin/sync;bin/sync;
	/bin/mount -r -o remount /
	/bin/sleep 1
	/sbin/reboot;
fi

if [ -f "/firstboot" ]; then
	echo "First boot... ";
	rm /firstboot
        END_SECTOR=`fdisk -l -u /dev/mmcblk0 | grep p2 | awk '{print $3}'`
        NEXT_SECTOR=$(( $END_SECTOR + 1 ));                               
        (echo n;echo p;echo 3;echo $NEXT_SECTOR;echo ;echo w;) | /sbin/fdisk -u -b 512 /dev/mmcblk0
	touch /secondboot
	echo "First boot done!";
	sync;sync;/sbin/reboot;
fi


fi

exit 0
